---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/data:/config
      - /path/to/movies:/multimidia/downloads/movies #optional
      - /path/to/downloadclient-downloads:/multimidia/lixeira #optional
    ports:
      - 7878:7878
    restart: unless-stopped
...
