#cloud-config
autoinstall:
  version: 1
  locale: pt_BR
  keyboard:
    layout: br
    variant: abnt2
  timezone: America/Sao_Paulo
  identity:
    hostname: ubuntu-bionexo
    username: mbionexo
    password: "$6$rJmYXoxnEctEZI1X$nF2bWyAaPlgTT7HUq0Xtuw9wGz0z58MYnKeYFWhLY4zZbQLz1epMOjZ.bz5Am6TQYxkLidD2AwEYr6WQK6QVr/"
  packages:
    - git
    - curl
  storage:
    layout:
      name: zfs
  ssh:
    install-server: true
  late-commands:
    - curtin in-target --target=/target -- curl https://192.168.10.15/Scripts/linux/installBionexo.sh | bash
  user-data:
    disable_root: false
    users:
      - default
    ssh_pwauth: true
    shell: /bin/bash
